
const data = [
    {
        id:48,
        name:"Blog App",
        image:"blogapp",
        url:"https://blog-app-with-firebase.vercel.app/",
        source:"https://github.com/MehmetCakir1/blogAppWithFirebase",
        tool:"react"
    },
    {
        id:47,
        name:"Contact App",
        image:"fireContact",
        url:"https://contact-app-with-firebase-db.vercel.app/",
        source:"https://github.com/MehmetCakir1/contactAppWithFirebaseDB",
        tool:"react"
    },
    {
        id:46,
        name:"Cocktails",
        image:"cocktails",
        url:"https://cocktail-website-with-context-api.vercel.app/",
        source:"https://github.com/MehmetCakir1/cocktailWebsiteWithContextAPI",
        tool:"react"
    },
    {
        id:45,
        name:"Movie App",
        image:"movieApp",
        url:"https://movie-app-with-firebase.vercel.app/",
        source:"https://github.com/MehmetCakir1/movieAppWithFirebase",
        tool:"react"
    },
    {
        id:44,
        name:"Stripe",
        image:"stripe",
        url:"https://stripe-project-with-context-api.vercel.app/",
        source:"https://github.com/MehmetCakir1/stripeProjectWithContextAPI",
        tool:"react"
    },
    {
        id:43,
        name:"SideBar",
        image:"sideBar",
        url:"https://side-bar-and-modal-with-context-api.vercel.app/",
        source:"https://github.com/MehmetCakir1/sideBarAndModalWithContextAPI",
        tool:"react"
    },
    {
        id:42,
        name:"NavBar",
        image:"navBar",
        url:"https://navbar-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/navbarWithReact",
        tool:"react"
    },
    {
        id:41,
        name:"Shopping List",
        image:"shoppingList",
        url:"https://shopping-list-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/shoppingListWithReact",
        tool:"react"
    },
    {
        id:40,
        name:"User App",
        image:"userApp",
        url:"https://user-app-with-react-router.vercel.app/",
        source:"https://github.com/MehmetCakir1/userAppWithReactRouter",
        tool:"react"
    },
    {
        id:39,
        name:"Random User",
        image:"randomUser",
        url:"https://random-user-two-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/randomUserTwoWithReact",
        tool:"react"
    },
    {
        id:38,
        name:"Recipe App",
        image:"recipeApp",
        url:"https://recipe-app-with-react-router.vercel.app/",
        source:"https://github.com/MehmetCakir1/recipeAppWithReactRouter",
        tool:"react"
    },
    {
        id:37,
        name:"Task Tracker",
        image:"taskTracker",
        url:"https://task-tracker-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/taskTrackerWithReact",
        tool:"react"
    },
    {
        id:36,
        name:"Color Generator",
        image:"colorGenerator",
        url:"https://color-generator-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/colorGeneratorWithReact",
        tool:"react"
    },
    {
        id:35,
        name:"Parag. Generator",
        image:"loremIpsum",
        url:"https://lorem-ipsum-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/loremIpsumProjectWithReact",
        tool:"react"
    },
    {
        id:34,
        name:"Slider",
        image:"slider",
        url:"https://slider-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/sliderProjectWithReact",
        tool:"react"
    },
    {
        id:33,
        name:"Menu",
        image:"menu",
        url:"https://menu-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/menuProjectWithReact",
        tool:"react"
    },
    {
        id:32,
        name:"Tabs",
        image:"tabs",
        url:"https://tabs-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/tabsProjectWithReact",
        tool:"react"
    },
    {
        id:31,
        name:"Reviews",
        image:"reviews",
        url:"https://reviews-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/reviewsProjectWithReact",
        tool:"react"
    },
    {
        id:30,
        name:"Accordion",
        image:"accordion",
        url:"https://accordion-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/accordionProjectWithReact",
        tool:"react"
    },
    {
        id:29,
        name:"Tours Project",
        image:"toursProject",
        url:"https://tours-project-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/toursProjectWithReact",
        tool:"react"
    },
    {
        id:28,
        name:"Info Card",
        image:"infoCard",
        url:"https://info-card-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/infoCardWithReact",
        tool:"react"
    },
    {
        id:27,
        name:"Random Card",
        image:"randomUserCard",
        url:"https://random-user-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/randomUserWithReact",
        tool:"react"
    },
    {
        id:26,
        name:"Language Card",
        image:"languageCard",
        url:"https://language-cards-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/languageCardsWithReact",
        tool:"react"
    },
    {
        id:25,
        name:"Tour Places",
        image:"tourPlaces",
        url:"https://tour-places-with-react.vercel.app/",
        source:"https://github.com/MehmetCakir1/tourPlacesWithReact",
        tool:"react"
    },
    {
        id:24,
        name:"ReviewCard",
        image:"reviewCard",
        url:"https://mehmetcakir1.github.io/reviewCardWithReact/",
        source:"https://github.com/MehmetCakir1/reviewCardWithReact",
        tool:"react"
    },
    {
        id:23,
        name:"StopWatch",
        image:"stopwatch",
        url:"https://mehmetcakir1.github.io/stopWatchWithJS/",
        source:"https://github.com/MehmetCakir1/stopWatchWithJS",
        tool:"javascript"
    },
    {
        id:22,
        name:"Country Info",
        image:"countryInfo",
        url:"https://mehmetcakir1.github.io/countryInfo/",
        source:"https://github.com/MehmetCakir1/countryInfo",
        tool:"javascript"
    },
    {
        id:21,
        name:"Digital Clock",
        image:"digitalClock",
        url:"https://mehmetcakir1.github.io/digitalClock/",
        source:"https://github.com/MehmetCakir1/digitalClock",
        tool:"javascript"
    },
    {
        id:20,
        name:"Boostrap5",
        image:"bootstrap",
        url:"https://mehmetcakir1.github.io/Bootstrap5Project/",
        source:"https://github.com/MehmetCakir1/Bootstrap5Project",
        tool:"css"
    },
    {
        id:19,
        name:"Guess",
        image:"guessTheNumber",
        url:"https://mehmetcakir1.github.io/guessTheNumberWithJS/",
        source:"https://github.com/MehmetCakir1/guessTheNumberWithJS",
        tool:"javascript"
    },
    {
        id:18,
        name:"Netflix Survey",
        image:"netflixSurveyForm",
        url:"https://mehmetcakir1.github.io/Netflix-Survey-Form/",
        source:"https://github.com/MehmetCakir1/Netflix-Survey-Form",
        tool:"css"
    },
    {
        id:17,
        name:"IOS Calculator",
        image:"iosCalculator",
        url:"https://mehmetcakir1.github.io/calculatorWithJS/",
        source:"https://github.com/MehmetCakir1/calculatorWithJS",
        tool:"javascript"
    },
    {
        id:16,
        name:"To Do List",
        image:"toDoList",
        url:"https://mehmetcakir1.github.io/toDoListWithJavascript/",
        source:"https://github.com/MehmetCakir1/toDoListWithJavascript",
        tool:"javascript"
    },
    {
        id:15,
        name:"Number Checker",
        image:"palindromAndPerfectNumber",
        url:"https://mehmetcakir1.github.io/palindromeAndPerfectNumberChecker.js/",
        source:"https://github.com/MehmetCakir1/palindromeAndPerfectNumberChecker.js",
        tool:"javascript"
    },
    {
        id:14,
        name:"Checkout Form",
        image:"checkoutForm",
        url:"https://mehmetcakir1.github.io/checkoutForm/",
        source:"https://github.com/MehmetCakir1/checkoutForm",
        tool:"javascript"
    },
    {
        id:13,
        name:"Random BgColor",
        image:"randomBackgroundColor",
        url:"https://mehmetcakir1.github.io/randomBackgroundColorWithJavascript/",
        source:"https://github.com/MehmetCakir1/randomBackgroundColorWithJavascript",
        tool:"javascript"
    },
    {
        id:12,
        name:"Sass Project",
        image:"sassProject",
        url:"https://mehmetcakir1.github.io/basicSassWork/",
        source:"https://github.com/MehmetCakir1/basicSassWork",
        tool:"css"
    },
    {
        id:11,
        name:"Parallax Website",
        image:"parallaxWebsite",
        url:"https://mehmetcakir1.github.io/Parallax_Website/",
        source:"https://github.com/MehmetCakir1/Parallax_Website",
        tool:"css"
    },
    {
        id:10,
        name:"Leap Year",
        image:"leapYear",
        url:"https://mehmetcakir1.github.io/Leap-Year/",
        source:"https://github.com/MehmetCakir1/Leap-Year",
        tool:"javascript"
    },
    {
        id:9,
        name:"Navbar",
        image:"hamburgerMenu",
        url:"https://mehmetcakir1.github.io/Nav-bar/",
        source:"https://github.com/MehmetCakir1/Nav-bar",
        tool:"javascript"
    },
    {
        id:8,
        name:"Preview Cards",
        image:"previewCards",
        url:"https://mehmetcakir1.github.io/Column-Preview-Card/",
        source:"https://github.com/MehmetCakir1/Column-Preview-Card",
        tool:"css"
    },
    {
        id:7,
        name:"Basic Form",
        image:"basicForm",
        url:"https://mehmetcakir1.github.io/Basic_form_2/",
        source:"https://github.com/MehmetCakir1/Basic_form_2",
        tool:"css"
    },
    {
        id:6,
        name:"Rolling Eggs",
        image:"rollingEggs",
        url:"https://mehmetcakir1.github.io/Rolling_eggs/",
        source:"https://github.com/MehmetCakir1/Rolling_eggs",
        tool:"css"
    },
    {
        id:5,
        name:"Basic Clock",
        image:"basicClock",
        url:"https://mehmetcakir1.github.io/Basic-Clock/",
        source:"https://github.com/MehmetCakir1/Basic-Clock",
        tool:"css"
    },
    {
        id:4,
        name:"Contact Form",
        image:"basicContactForm",
        url:"https://mehmetcakir1.github.io/Basic-Form/",
        source:"https://github.com/MehmetCakir1/Basic-Form",
        tool:"css"
    },
    {
        id:3,
        name:"Chessboard",
        image:"Chessboard",
        url:"https://mehmetcakir1.github.io/Chessboard/",
        source:"https://github.com/MehmetCakir1/Chessboard",
        tool:"css"
    },
    {
        id:2,
        name:"Falling Boxes",
        image:"fallingBoxes",
        url:"https://mehmetcakir1.github.io/Falling_Box/",
        source:"https://github.com/MehmetCakir1/Falling_Box",
        tool:"css"
    },
    {
        id:1,
        name:"JS-Algorithms",
        image:"jsalgorithms",
        url:"https://github.com/MehmetCakir1/javascriptAlgorithms",
        source:"https://github.com/MehmetCakir1/javascriptAlgorithms",
        tool:"javascript"
    },
    ]
    
    export default data